<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd



 Massivga yo'naltirilgan dasturlash
Arifmetik amallar
Ko'paytirish, bo'lish, qo'shish, ayirish va h.k amallar

In [12]:
arr1=np.arange(6).reshape(2, 3)  # 0~6 gach bo'lgan elementlardan tashkil topgan array
arr2=np.arange(6,12).reshape(2,3)

In [10]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
arr1*arr2 # arr1 ning elementlarini arr2 ning mos elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [16]:
arr1/arr2 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [17]:
arr1+arr2  # arr1 ning elementlarini arr2 ning mos elementlariga qo'shib beradi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [18]:
arr1-arr2 # arr2 ning elementlaridan arr1 mos elementlarini ayirish

array([[-6, -6, -6],
       [-6, -6, -6]])

In [19]:
# kvadratga oshirish (square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [20]:
# kvadrat ildizdan (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])