<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/boolean_indexlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd
import numpy as np


N-o'lchamli massiv (array)larga ishlov berish
Bolean Indekslash

In [58]:
names=np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [59]:
data=np.random.randn(7,4)
data

array([[ 1.37916529,  0.77773197, -0.15075241,  0.47146749],
       [-0.75838475,  0.25109889, -0.40252481, -0.4774771 ],
       [-0.68899972,  1.90328029,  1.05757109,  0.65897327],
       [ 0.42805994, -2.29005252,  0.3630752 ,  1.27618796],
       [-1.17815568, -0.12814744, -0.38208308, -0.81525547],
       [ 0.26400993,  0.11199416, -0.97811718,  0.07986373],
       [-0.29142805, -0.37766368,  1.56075477, -0.22639995]])

In [60]:
names=='Hasan'

array([ True, False, False, False,  True, False, False])

In [61]:
data[names=='Hasan']

array([[ 1.37916529,  0.77773197, -0.15075241,  0.47146749],
       [-1.17815568, -0.12814744, -0.38208308, -0.81525547]])

In [62]:
names=='Elyor'

array([False, False, False,  True, False, False,  True])

In [63]:
data[names=='Elyor']

array([[ 0.42805994, -2.29005252,  0.3630752 ,  1.27618796],
       [-0.29142805, -0.37766368,  1.56075477, -0.22639995]])

In [64]:
data[names=='Hasan',2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish


array([[-0.15075241,  0.47146749],
       [-0.38208308, -0.81525547]])

In [65]:
data[names!='Hasan']  # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish


array([[-0.75838475,  0.25109889, -0.40252481, -0.4774771 ],
       [-0.68899972,  1.90328029,  1.05757109,  0.65897327],
       [ 0.42805994, -2.29005252,  0.3630752 ,  1.27618796],
       [ 0.26400993,  0.11199416, -0.97811718,  0.07986373],
       [-0.29142805, -0.37766368,  1.56075477, -0.22639995]])

In [66]:
data[~(names=='Hasan')] # (~) yuqoridagi cell bilan bir xil natijani berar ekan
# names!='Hasan

array([[-0.75838475,  0.25109889, -0.40252481, -0.4774771 ],
       [-0.68899972,  1.90328029,  1.05757109,  0.65897327],
       [ 0.42805994, -2.29005252,  0.3630752 ,  1.27618796],
       [ 0.26400993,  0.11199416, -0.97811718,  0.07986373],
       [-0.29142805, -0.37766368,  1.56075477, -0.22639995]])

In [67]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 1.37916529  0.77773197 -0.15075241  0.47146749]
 [-0.75838475  0.25109889 -0.40252481 -0.4774771 ]
 [-0.68899972  1.90328029  1.05757109  0.65897327]
 [ 0.42805994 -2.29005252  0.3630752   1.27618796]
 [-1.17815568 -0.12814744 -0.38208308 -0.81525547]
 [ 0.26400993  0.11199416 -0.97811718  0.07986373]
 [-0.29142805 -0.37766368  1.56075477 -0.22639995]]


In [68]:
mask=(names=='Hasan')|(names=='Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [69]:
data[mask]

array([[ 1.37916529,  0.77773197, -0.15075241,  0.47146749],
       [-0.75838475,  0.25109889, -0.40252481, -0.4774771 ],
       [-1.17815568, -0.12814744, -0.38208308, -0.81525547]])

In [70]:
data[data<0]=0
data

array([[1.37916529, 0.77773197, 0.        , 0.47146749],
       [0.        , 0.25109889, 0.        , 0.        ],
       [0.        , 1.90328029, 1.05757109, 0.65897327],
       [0.42805994, 0.        , 0.3630752 , 1.27618796],
       [0.        , 0.        , 0.        , 0.        ],
       [0.26400993, 0.11199416, 0.        , 0.07986373],
       [0.        , 0.        , 1.56075477, 0.        ]])

In [71]:
data

array([[1.37916529, 0.77773197, 0.        , 0.47146749],
       [0.        , 0.25109889, 0.        , 0.        ],
       [0.        , 1.90328029, 1.05757109, 0.65897327],
       [0.42805994, 0.        , 0.3630752 , 1.27618796],
       [0.        , 0.        , 0.        , 0.        ],
       [0.26400993, 0.11199416, 0.        , 0.07986373],
       [0.        , 0.        , 1.56075477, 0.        ]])