<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np



In [48]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
y=np.array([[4.,4.,4.],[5.,5.,5.]])
y

array([[4., 4., 4.],
       [5., 5., 5.]])

In [50]:
x+y

array([[ 5.,  6.,  7.],
       [ 9., 10., 11.]])

In [51]:
y-x

array([[ 3.,  2.,  1.],
       [ 1.,  0., -1.]])

In [52]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [53]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [54]:
y=np.array([[23.,7],[-2.,3.],[6.,-4.]])
y

array([[23.,  7.],
       [-2.,  3.],
       [ 6., -4.]])

In [55]:
x.dot(y) # x*y

array([[ 37.,   1.],
       [118.,  19.]])

In [56]:
np.dot(x,y)

array([[ 37.,   1.],
       [118.,  19.]])

In [57]:
y.dot(x)  # y*x

array([[ 51.,  81., 111.],
       [ 10.,  11.,  12.],
       [-10.,  -8.,  -6.]])

In [58]:
np.dot(y,x)

array([[ 51.,  81., 111.],
       [ 10.,  11.,  12.],
       [-10.,  -8.,  -6.]])