<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np



save-tarkibida faqat bitta array saqlaydi va ikkilik sanoq sestemasida saqlaydi.
savetxt-bitta arrayni text ko'rinishida saqlaydi.
savez-tarkibida bir necha arrayni saqlaydi.
savez_compressed-sevez bilan bir xil faqat fayl hajmini kichiklashtirib siqib beradi.

In [20]:
arr=np.arange(10)

In [24]:
np.save('data.npy', arr)

In [26]:
arr2=np.load('data.npy')

In [27]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr1=np.arange(20)

In [30]:
np.savez('array', a=arr, b=arr1)

In [34]:
arrays=np.load('array.npz')

In [35]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
np.savez_compressed('array_comp.npz',a=arr,b=arr1)

In [42]:
fewe=np.load('array_comp.npz')

In [43]:
fewe['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
fewe['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])