<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/indexlash_va_kesish_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


 N-o'lchamli massiv (array)larga ishlov berish
Indeks va kesib olish asoslari

In [2]:
arr=np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
arr[-2]

80

In [4]:
arr[3:5]

array([40, 50])

In [6]:
arr[:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Numpy kutubxonasida massivning kesib olingan qismga o'zgartirish kirtilinsa, asosiy manba massivga ta'sir qiladi.

In [9]:
sliced_arr=arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [10]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [11]:
arr1=np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
sliced_arr1=arr1[3:6].copy()
sliced_arr1[:]=0
sliced_arr1

array([0, 0, 0])

In [16]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

2 o'lchamli (2d array) massivlarda indeks va kesib olish


In [18]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])  # (3, 3) o'lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d[1,1]

5

In [28]:
arr2d[1:2,1:]

array([[5, 6]])

In [29]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [23]:
arr2d[2,1]

8

In [24]:
sl_arr2d=arr2d[2,1:]
sl_arr2d

array([8, 9])

In [27]:
arr2d[2:,:]

array([[7, 8, 9]])

In [25]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

3-o'lchamli massivlarda indeks va kesib olish asoslari

In [30]:
arr3d=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]],
                [[19,20,21],
                 [22,23,24],
                 [25,26,27]]
])

In [31]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [33]:
arr3d[0][2,1]

8

In [34]:
arr3d[1][1,2]

15

In [35]:
arr3d[1][2,2]

18