<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/statisti_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd



. Massivga yo'naltirilgan dasturlash
Matematik va Statistik usullarni qo'llash

In [44]:
arr=np.random.randn(5,4)  # (5, 4) o'lchovli massiv (random)
arr

array([[-0.45540254, -0.18062046, -0.63565079,  0.58689711],
       [-1.29062942, -1.0510313 , -0.32573296, -0.7782713 ],
       [ 1.77342755,  1.6138695 , -0.32670617, -0.07105604],
       [ 1.38053707, -0.18100648,  1.95718905,  1.00202916],
       [ 0.18658333, -0.12149397,  0.29844408,  0.66256485]])

In [45]:
arr.sum()  # arr ning barcha elementlarni yig'indisini hisoblab beradi



4.043940289554577

In [46]:
np.sum(arr)  # arr ning barcha elementlarni yig'indisini hisoblab beradi


4.043940289554577

In [47]:
arr.sum(axis=1) # qator yi'gindi

array([-0.68477667, -3.44566498,  2.98953484,  4.15874881,  1.02609829])

In [48]:
arr.sum(axis=0) # ustun yig'indisini hisoblab beradi

array([1.594516  , 0.07971729, 0.96754322, 1.40216377])

In [49]:
data=np.arange(5)# 0 ~ 5 gacha bo'lgan elementlarda tashkil topgan massiv
data

array([0, 1, 2, 3, 4])

In [50]:
len(data)

5

In [51]:
mean=np.sum(data)/len(data)
mean

2.0

In [52]:
np.mean(data)

2.0

In [53]:
data.mean()

2.0

In [54]:
arr

array([[-0.45540254, -0.18062046, -0.63565079,  0.58689711],
       [-1.29062942, -1.0510313 , -0.32573296, -0.7782713 ],
       [ 1.77342755,  1.6138695 , -0.32670617, -0.07105604],
       [ 1.38053707, -0.18100648,  1.95718905,  1.00202916],
       [ 0.18658333, -0.12149397,  0.29844408,  0.66256485]])

In [55]:
np.mean(arr)

0.20219701447772884

In [56]:
arr.mean()

0.20219701447772884

In [57]:
np.mean(arr, axis=1)# qator bo'yich o'rtach qiymatni qaytaradi

array([-0.17119417, -0.86141624,  0.74738371,  1.0396872 ,  0.25652457])

In [58]:
arr.mean(axis=0)# ustunlar bo'yich o'rtach qiymatni qaytaradi

array([0.3189032 , 0.01594346, 0.19350864, 0.28043275])

In [59]:
data.cumsum()

array([ 0,  1,  3,  6, 10])