<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/tartiblash(sorting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd



Massivga yo'naltirilgan dasturlash
Tartiblash (Sorting)

In [69]:
arr=np.random.randn(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([ 0.15765547,  0.96678448,  0.37887742, -0.021472  ])

In [70]:
sorted_arr=np.sort(arr) # arr massivini tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([-0.021472  ,  0.15765547,  0.37887742,  0.96678448])

In [71]:
arr.sort()# arr ning tartiblangan ko'rinishi
arr

array([-0.021472  ,  0.15765547,  0.37887742,  0.96678448])

In [73]:
# teskari tartiblash
rev_arr=-np.sort(-arr)
rev_arr

array([ 0.96678448,  0.37887742,  0.15765547, -0.021472  ])

In [74]:
arr2d=np.random.randn(2, 4) #2 D array (massiv)
arr2d

array([[-0.12709482,  0.64616999,  1.5520358 , -0.81444689],
       [ 0.40765249,  1.45307854, -0.45869642, -0.81076076]])

In [ ]:
# axis = 0 --> Qator

In [75]:
raw_srt=np.sort(arr2d, axis=0)  # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
raw_srt

array([[-0.12709482,  0.64616999, -0.45869642, -0.81444689],
       [ 0.40765249,  1.45307854,  1.5520358 , -0.81076076]])

In [77]:
col_str=np.sort(arr2d, axis=1) # arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi
col_str

array([[-0.81444689, -0.12709482,  0.64616999,  1.5520358 ],
       [-0.81076076, -0.45869642,  0.40765249,  1.45307854]])