<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/Transpose_swapaxes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


 N-o'lchamli massiv (array)larga ishlov berish
Massivlar pozitsiyasini ko'chirish Transpose va o'qlar o'rnini almashtirish Swapping axes
reshape metodi

In [3]:
A=np.arange(6).reshape(3,2) # A massiv : Elementlari 0~6 gacha , shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

Trasnpose

In [4]:
A.T  # A massivning Trasnpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

swaping axes

In [5]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.swapaxes(1,0)  # A massivning Transpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
np.dot(A, A.T) # A va A^T (A massivni transposeidan) hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])