<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/Universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


Unary funksiyalar (bitta argument qabul qiluvchi funkisya)
sqrt, square, exp, log, modf, sign, isnan funksiyalarini ko'rib chiqamiz


In [8]:
arr=np.arange(10) # 0 ~ 10 gacha bo'lgan elementlardan iborat massivni qaytaradi
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sqrt massivning xar bir elementini kvadrat ildizni qaytaradi


In [9]:
np.sqrt(arr) # arr nomli massivning barcha elementlaridan kv ildizni qaytaradi


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.square(arr) #square massivning xar bir elementini kvadratga oshiradi


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

exp massivning xar bir elementini eksponentini qaytaradi


In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

log massivning xar bir logorifmini hisoblaydi

In [14]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
arr1=np.random.randn(6)
arr1

array([ 0.25671513,  0.2807004 ,  1.69194515,  0.86731024,  0.99901729,
       -0.66798746])

modf bu funksiya haqiqiy sonlarni butun va qoldiq qismlarini ajratib beruvchi funksiya


In [16]:
qoldiq, butun=np.modf(arr1)# arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratadi


In [17]:
print(qoldiq)
print(butun)

[ 0.25671513  0.2807004   0.69194515  0.86731024  0.99901729 -0.66798746]
[ 0.  0.  1.  0.  0. -0.]


sign funkisyasi massiv elementlarini qiymati manfiy bo'lsa -1 va aksincha musbat bo'lsa 1 ni qaytaradi


In [18]:
np.sign(arr1)

array([ 1.,  1.,  1.,  1.,  1., -1.])

In [20]:
arr1

array([ 0.25671513,  0.2807004 ,  1.69194515,  0.86731024,  0.99901729,
       -0.66798746])

In [19]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [21]:
arr1[0]=np.NaN

In [22]:
arr1

array([        nan,  0.2807004 ,  1.69194515,  0.86731024,  0.99901729,
       -0.66798746])

In [30]:
np.rint(arr1) # butun son ko'rinishida yaxlitlaydi

array([nan,  0.,  2.,  1.,  1., -1.])

Binary funksiyalar (ikkita argument qabul qiluvchi funkisya)
add, multiply, maximum funksiyalarini ko'rib chiqamiz
add ikkita massivning mos elementlarini qo'shadi


In [31]:
arr2=np.random.randn(6)
arr3=np.random.randn(6)

In [32]:
arr2

array([-0.91318293,  0.06960202, -0.53896898, -0.44971209,  1.20797925,
        2.01150849])

In [33]:
arr3

array([-0.46474793, -0.50110734, -2.42789284, -1.00379141,  0.56127771,
        0.94262625])

In [34]:
np.add(arr2, arr3)

array([-1.37793086, -0.43150532, -2.96686181, -1.4535035 ,  1.76925696,
        2.95413475])

In [35]:
arr2+arr3

array([-1.37793086, -0.43150532, -2.96686181, -1.4535035 ,  1.76925696,
        2.95413475])

In [36]:
np.multiply(arr2, arr3) #multiply ikkita massivning mos elementlarini ko'paytiradi


array([ 0.42439987, -0.03487808,  1.30855892,  0.45141714,  0.67801183,
        1.89610072])

maximum ikkita massivning elementlarin taqqoslab ulardan kattasining qiymatini qaytaradi

In [37]:
np.maximum(arr2, arr3)

array([-0.46474793,  0.06960202, -0.53896898, -0.44971209,  1.20797925,
        2.01150849])