<a href="https://colab.research.google.com/github/javmohir/data_science/blob/main/where_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd



Massivga yo'naltirilgan dasturlash
Mantiqiy shart operatorlarni massiv operator sifatida qo'llash
Shart operatori sifatida where dan foydalanish
Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: xarr va yarr. Agarda shart Trueni qanoatlantirsa xarr elementini qabul qilgan aksincha esa yarr elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
# Massivlar
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5])# xarr
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])# yarr

In [3]:
# shart
cond=np.array([True, False, True, True, False])

In [4]:
# where
resalt=np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
resalt

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
arr=np.random.randn(4,4)
arr

array([[ 1.37285134,  0.83261202, -0.23797538,  0.51993011],
       [-3.87207032, -0.02287996,  1.6524944 ,  0.24832713],
       [ 1.05503842, -1.62103499,  1.00771247, -1.74415159],
       [-0.68963088,  0.14862699, -0.11809516,  1.07752055]])

In [7]:
results=np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[ 2,  2, -2,  2],
       [-2, -2,  2,  2],
       [ 2, -2,  2, -2],
       [-2,  2, -2,  2]])